#!/usr/bin/env bash
set -euo pipefail

if [[ ! -f scripts/run_inference.py || ! -f scripts/run_evaluation.py ]]; then
  echo "[ERROR] Run this from the MindCube repo root." >&2
  exit 1
fi

RUN_ID="${RUN_ID:-gemma4-31b-cluster40gb-bf16-noquant-baseline-raw-qa-50}"
RUN_ROOT="${RUN_ROOT:-experiments/runs}"
RUN_DIR="${RUN_ROOT%/}/${RUN_ID}"
SOURCE_INPUT="${SOURCE_INPUT:-data/prompts/general/MindCube_tinybench_raw_qa.jsonl}"
IMAGE_ROOT="${IMAGE_ROOT:-./data/}"
CONFIG_PATH="${CONFIG_PATH:-experiments/configs/gemma4_31b_cluster40gb_bf16_noquant_reasoning_greedy_inference.json}"
MODEL_PATH="${MODEL_PATH:-google/gemma-4-31B-it}"
SAMPLE_COUNT="${SAMPLE_COUNT:-50}"
MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-1024}"
BATCH_SIZE="${BATCH_SIZE:-1}"
GPU_GROUPS="${GPU_GROUPS:-0,1 2,3}"

mkdir -p "$RUN_DIR"/{logs,shards}

if [[ ! -f "$SOURCE_INPUT" ]]; then
  echo "[ERROR] Missing source input: $SOURCE_INPUT" >&2
  exit 1
fi
if [[ ! -f "$CONFIG_PATH" ]]; then
  echo "[ERROR] Missing inference config: $CONFIG_PATH" >&2
  exit 1
fi

INPUT_50="$RUN_DIR/input_${SAMPLE_COUNT}.jsonl"
head -n "$SAMPLE_COUNT" "$SOURCE_INPUT" > "$INPUT_50"
actual_count="$(wc -l < "$INPUT_50" | tr -d ' ')"
if [[ "$actual_count" -eq 0 ]]; then
  echo "[ERROR] Empty input after sampling: $INPUT_50" >&2
  exit 1
fi

read -r -a GROUP_ARRAY <<< "$GPU_GROUPS"
SHARD_COUNT="${#GROUP_ARRAY[@]}"
if [[ "$SHARD_COUNT" -lt 1 ]]; then
  echo "[ERROR] GPU_GROUPS is empty." >&2
  exit 1
fi

python - "$INPUT_50" "$RUN_DIR/shards" "$SHARD_COUNT" <<'PY'
import math
import sys
from pathlib import Path

input_path = Path(sys.argv[1])
shard_dir = Path(sys.argv[2])
shard_count = int(sys.argv[3])
lines = input_path.read_text(encoding="utf-8").splitlines()
per_shard = max(1, math.ceil(len(lines) / shard_count))

for index in range(shard_count):
    start = index * per_shard
    end = min(len(lines), start + per_shard)
    shard_path = shard_dir / f"input_shard_{index:02d}.jsonl"
    shard_lines = lines[start:end]
    shard_path.write_text(
        "\n".join(shard_lines) + ("\n" if shard_lines else ""),
        encoding="utf-8",
    )
PY

python - "$RUN_ID" "$RUN_DIR" "$CONFIG_PATH" "$MODEL_PATH" "$INPUT_50" "$IMAGE_ROOT" "$MAX_NEW_TOKENS" "$BATCH_SIZE" <<'PY'
import datetime as dt
import json
import subprocess
import sys
from pathlib import Path

run_id, run_dir, config_path, model_path, input_file, image_root, max_new_tokens, batch_size = sys.argv[1:]
run_dir = Path(run_dir)

config = {
    "name": run_id,
    "description": "Gemma 4 31B BF16 no-quant raw QA baseline on 50 MindCube examples.",
    "hypothesis": "Removing 4-bit quantization should preserve Gemma 4 visual perception and give a valid 31B baseline.",
    "tags": [
        "baseline",
        "raw_qa",
        "gemma4",
        "31b",
        "cluster40gb",
        "bf16",
        "noquant",
        "greedy",
        "transformers",
        "50",
    ],
    "model": {
        "type": "gemma4",
        "path": model_path,
        "backend": "transformers",
        "inference_config": config_path,
    },
    "data": {
        "split": "tinybench",
        "task": "raw_qa",
        "input_file": input_file,
        "image_root": image_root,
    },
    "generation": {
        "batch_size": int(batch_size),
        "max_new_tokens": int(max_new_tokens),
        "temperature": 0.0,
        "top_p": 1.0,
    },
    "evaluation": {"mode": "basic"},
}
(run_dir / "config.json").write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")

def git(*args: str) -> str:
    try:
        return subprocess.check_output(["git", *args], text=True).strip()
    except Exception:
        return ""

manifest = {
    "run_id": run_id,
    "started_at": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat(),
    "status": "running",
    "config_source": "generated by scripts/bash_scripts/run_gemma4_noquant_raw_qa_50_cluster.bash",
    "git": {
        "commit": git("rev-parse", "--short", "HEAD") or "unknown",
        "branch": git("branch", "--show-current") or "unknown",
        "dirty": bool(git("status", "--short")),
    },
    "artifacts": {
        "predictions": f"{run_dir}/predictions.jsonl",
        "evaluation": f"{run_dir}/evaluation.json",
        "metrics": f"{run_dir}/metrics.json",
        "dashboard": f"{run_dir}/dashboard.html",
        "notes": f"{run_dir}/notes.md",
        "log": f"{run_dir}/logs/run.log",
    },
}
(run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

notes = f"""# {run_id}

## Question
Does Gemma 4 31B work as a valid baseline when run in BF16 without 4-bit quantization?

## Setup
- Model: {model_path}
- Inference config: {config_path}
- Prompt/task: raw_qa
- Samples: {input_file}
- GPU groups: set by GPU_GROUPS

## Result
Fill in after the run.

## Observations
- 

## Decision
- Status: undecided
"""
(run_dir / "notes.md").write_text(notes, encoding="utf-8")
PY

echo "[INFO] Run: $RUN_ID"
echo "[INFO] Samples: $actual_count"
echo "[INFO] GPU groups: $GPU_GROUPS"

pids=()
for index in "${!GROUP_ARRAY[@]}"; do
  shard_id="$(printf "%02d" "$index")"
  shard_input="$RUN_DIR/shards/input_shard_${shard_id}.jsonl"
  shard_output="$RUN_DIR/shards/predictions_shard_${shard_id}.jsonl"
  shard_log="$RUN_DIR/logs/gpu_group_${shard_id}.log"
  gpu_group="${GROUP_ARRAY[$index]}"

  if [[ ! -s "$shard_input" ]]; then
    echo "[INFO] Skipping empty shard $shard_id"
    continue
  fi

  echo "[INFO] Starting shard $shard_id on CUDA_VISIBLE_DEVICES=$gpu_group"
  (
    CUDA_VISIBLE_DEVICES="$gpu_group" python scripts/run_inference.py \
      --model-type gemma4 \
      --model-path "$MODEL_PATH" \
      --backend transformers \
      --input-file "$shard_input" \
      --output-file "$shard_output" \
      --image-root "$IMAGE_ROOT" \
      --batch-size "$BATCH_SIZE" \
      --max-new-tokens "$MAX_NEW_TOKENS" \
      --temperature 0.0 \
      --top-p 1.0 \
      --config "$CONFIG_PATH" \
      --multi-gpu
  ) > "$shard_log" 2>&1 &
  pids+=("$!")
done

failed=0
for pid in "${pids[@]}"; do
  if ! wait "$pid"; then
    failed=1
  fi
done

if [[ "$failed" -ne 0 ]]; then
  echo "[ERROR] At least one shard failed. Check logs in $RUN_DIR/logs" >&2
  exit 1
fi

cat "$RUN_DIR"/shards/predictions_shard_*.jsonl > "$RUN_DIR/predictions.jsonl"
pred_count="$(wc -l < "$RUN_DIR/predictions.jsonl" | tr -d ' ')"
echo "[INFO] Merged predictions: $pred_count/$actual_count"

python scripts/run_evaluation.py \
  --input "$RUN_DIR/predictions.jsonl" \
  --output "$RUN_DIR/evaluation.json" \
  --task basic

python - "$RUN_DIR/evaluation.json" "$RUN_DIR/metrics.json" <<'PY'
import json
import sys
from pathlib import Path

evaluation = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
results = evaluation.get("results", {})
accuracy = results.get("gen_cogmap_accuracy")
settings = {}
for setting, values in results.get("settings", {}).items():
    setting_accuracy = values.get("gen_cogmap_accuracy")
    settings[setting] = {
        "total": values.get("total", 0),
        "correct": values.get("gen_cogmap_correct", 0),
        "accuracy": round(float(setting_accuracy) * 100, 4) if isinstance(setting_accuracy, (int, float)) else None,
    }
metrics = {
    "accuracy": round(float(accuracy) * 100, 4) if isinstance(accuracy, (int, float)) else None,
    "total": results.get("total", 0),
    "correct": results.get("gen_cogmap_correct", 0),
    "unfiltered_total": results.get("unfiltered_total", results.get("total", 0)),
    "settings": settings,
}
Path(sys.argv[2]).write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")
PY

python scripts/export_model_view_images.py \
  --run-dir "$RUN_DIR" \
  --image-root "$IMAGE_ROOT"

python - "$RUN_DIR" <<'PY'
import datetime as dt
import json
import sys
from pathlib import Path

run_dir = Path(sys.argv[1])
manifest_path = run_dir / "manifest.json"
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
manifest["status"] = "success"
manifest["completed_at"] = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
PY

python scripts/analyze_run.py \
  --run-dir "$RUN_DIR" \
  --sample-limit 50

echo "[INFO] Done."
echo "[INFO] Dashboard: $RUN_DIR/dashboard.html"
echo "[INFO] Predictions: $RUN_DIR/predictions.jsonl"
